FROM node:20-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm install --legacy-peer-deps
COPY backend/ .
RUN npm run build

# Runtime
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache tzdata procps util-linux
COPY --from=0 /app/dist ./dist
COPY --from=0 /app/package*.json ./
RUN npm install --omit=dev --legacy-peer-deps
EXPOSE 3000
# Limit Node.js heap and optimize for memory
CMD ["node", "--max-old-space-size=112", "--optimize-for-size", "dist/main"]
