FROM node:20-alpine AS builder

WORKDIR /app
COPY backend/package*.json ./
RUN npm install --legacy-peer-deps
COPY backend/ .
RUN npm run build

# Runtime
FROM node:20-alpine

WORKDIR /app
ENV NODE_ENV=production
ENV TZ=America/Argentina/Mendoza

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package*.json ./
RUN npm install --omit=dev --legacy-peer-deps

EXPOSE 3000
CMD ["node", "--max-old-space-size=112", "--optimize-for-size", "dist/main"]
