FROM node:20-alpine
WORKDIR /app
COPY backend/package*.json ./
RUN npm install
COPY backend/ .
RUN npm run build

# Runtime
FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
RUN apk add --no-cache tzdata procps util-linux
COPY --from=0 /app/dist ./dist
COPY --from=0 /app/package*.json ./
RUN npm install --omit=dev
EXPOSE 3000
# Limit Node.js heap to 80MB and optimize for low memory footprint
CMD ["node", "--max-old-space-size=80", "--optimize-for-size", "--gc-interval=200", "dist/main"]
